const NAMESPACE = "PLANNING_POKER";

export const LOGIN_USER = `${NAMESPACE}/LOGIN_USER`;
export const LOGOUT_USER = `${NAMESPACE}/LOGOUT_USER`;
export const SET_CURRENT_GAME = `${NAMESPACE}/SET_CURRENT_GAME`;
export const CLEAR_CURRENT_GAME = `${NAMESPACE}/CLEAR_CURRENT_GAME`;
export const ADD_TASK = `${NAMESPACE}/ADD_TASK`;
export const VOTE_TASK = `${NAMESPACE}/VOTE_TASK`;
export const LOAD_VOTES_DISTRIBUTION = `${NAMESPACE}/LOAD_VOTES_DISTRIBUTION`;
export const LOAD_USER_GAMES = `${NAMESPACE}/LOAD_USER_GAMES`;

export const WS_CAST_VOTE = "WS_CAST_VOTE";
export const WS_PUBLISHED_TASK = "WS_PUBLISHED_TASK";
